import { registerAs } from '@nestjs/config';
import {
  DEFAULT_COOKIE_EXPIRES_IN_MILLISECOND,
  DEFAULT_REFRESH_TOKEN_COOKIE_EXPIRES_IN_MILLISECOND,
  ONE_DAY_IN_MILL_SEC,
  ONE_MINUTE_IN_MILL_SEC,
  PROCONNECT_DOMAIN,
} from '../constants';

export default registerAs('jwtConfig', () => ({
  // JWT-AUTH
  JWT_STRATEGY_SECRET: process.env.JWT_STRATEGY_SECRET || 'aptechsecretjwt',
  JWT_ACCESS_TOKEN_EXPIRES_IN: process.env.JWT_ACCESS_TOKEN_EXPIRES_IN || '50m',
  JWT_STRATEGY_REFRESH_TOKEN_SECRET:
    process.env.JWT_STRATEGY_REFRESH_TOKEN_SECRET || 'aptechrefreshsecretjwt',
  JWT_REFRESH_TOKEN_EXPIRES_IN: process.env.JWT_REFRESH_TOKEN_EXPIRES_IN || '30d',
  // JWT-COOKIE

  COOKIE_EXPIRES_IN_MILLISECOND: process.env.COOKIE_EXPIRES_IN_MIN
    ? ONE_MINUTE_IN_MILL_SEC * Number(process.env.COOKIE_EXPIRES_IN_MIN)
    : DEFAULT_COOKIE_EXPIRES_IN_MILLISECOND,

  REFRESH_TOKEN_COOKIE_EXPIRES_IN_MILLISECOND: process.env
    .REFRESH_TOKEN_COOKIE_EXPIRES_IN_DAYS
    ? ONE_DAY_IN_MILL_SEC * Number(process.env.REFRESH_TOKEN_COOKIE_EXPIRES_IN_DAYS)
    : DEFAULT_REFRESH_TOKEN_COOKIE_EXPIRES_IN_MILLISECOND,

  COOKIE_DOMAIN: process.env.COOKIE_DOMAIN || PROCONNECT_DOMAIN,
  // JWT-OTP
  OTP_SECRET: process.env.OTP_SECRET || 'aptechotpsecret',
  FORGOT_PASSWORD_SECRET:
    process.env.FORGOT_PASSWORD_SECRET || 'aptechforgotpasswordsecret',
}));
